AUGMENTATION: true
PARAMS_IMAGE_SIZE: [140, 140, 1]
PARAMS_LEARNING_RATE: 0.001
PARAMS_INCLUDE_TOP: false
PARAMS_WEIGHTS: null
PARAMS_CLASSES: 4
PARAMS_BATCH_SIZE: 32
PARAMS_EPOCHS: 60
PARAMS_PATIENTS: 5
PARAMS_MONITOR: "val_loss"
PARAMS_MODE: "min"